#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
config device-configurator qspi-configurator smartio-configurator bsp-assistant config_ezpd ez-pd-configurator seglcd-configurator modlibs library-manager config_usbdev usbdev-configurator dfuh-tool :
	make -C proj_cm33_s $@

config_lin lin-configurator config_bt bt-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: config device-configurator qspi-configurator smartio-configurator config_lin lin-configurator config_bt bt-configurator bsp-assistant config_ezpd ez-pd-configurator seglcd-configurator modlibs library-manager config_usbdev usbdev-configurator dfuh-tool
